version: '3.8'

services:
  financial_organizer:
    container_name: financial_organizer
    build: .
    volumes:
      - ./.env:/.env
    deploy:
      resources:
        limits:
          memory: "1G"
    ports:
      - "5000:5000"
