// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Renan Lourenço",
            "url": "https://github.com/RenanLourenco",
            "email": "renanloub@protonmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/expense/:id": {
            "get": {
                "description": "Get specific expense",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Expense"
                ],
                "summary": "Get specific expense",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/get_expense.GetExpenseOutput"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete specific expense",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Expense"
                ],
                "summary": "Delete specific expense",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delete_expense.DeleteExpenseOutput"
                        }
                    }
                }
            }
        },
        "/expenses": {
            "post": {
                "description": "Create a new expense",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Expense"
                ],
                "summary": "Create a new expense",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/create_expense.CreateExpenseDtoOutput"
                        }
                    }
                }
            }
        },
        "/expenses/:id": {
            "put": {
                "responses": {}
            }
        },
        "/expenses/:year/:month": {
            "get": {
                "description": "List expenses by month",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Expense"
                ],
                "summary": "List expenses by month",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/list_expenses.ListExpenseOutput"
                        }
                    }
                }
            }
        },
        "/income/:id": {
            "get": {
                "description": "Get specific income by id",
                "tags": [
                    "Income"
                ],
                "summary": "Get specific income by id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/get_income.GetIncomeOutput"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete income",
                "tags": [
                    "Income"
                ],
                "summary": "delete income",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/delete_income.DeleteIncomeOutput"
                        }
                    }
                }
            }
        },
        "/incomes": {
            "get": {
                "description": "List incomes",
                "tags": [
                    "Income"
                ],
                "summary": "List incomes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/list_incomes.ListIncomesOutput"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new income",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Income"
                ],
                "summary": "Create a new income",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/create_income.CreateIncomeOutput"
                        }
                    }
                }
            }
        },
        "/incomes/:year/:month": {
            "get": {
                "description": "Get specific incomes by month",
                "tags": [
                    "Income"
                ],
                "summary": "Get specific incomes by month",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/list_income_by_month.ListIncomeByMonthOutput"
                        }
                    }
                }
            }
        },
        "/resume/:year/:month": {
            "get": {
                "description": "return a month resume about registered financial in month",
                "tags": [
                    "Resume"
                ],
                "summary": "return a month resume about registered financial in month",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/month_resume.MonthResumeOutput"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "create_expense.CreateExpenseDtoOutput": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/entity.Category"
                },
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "create_income.CreateIncomeOutput": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "delete_expense.DeleteExpenseOutput": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "delete_income.DeleteIncomeOutput": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string"
                }
            }
        },
        "entity.Category": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "expenses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Expense"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entity.Expense": {
            "type": "object",
            "properties": {
                "categoryID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "entity.Income": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "get_expense.GetExpenseOutput": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "get_income.GetIncomeOutput": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "list_expense_by_month.ListExpenseByMonthOutput": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Expense"
                    }
                }
            }
        },
        "list_expenses.ListExpenseOutput": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Expense"
                    }
                }
            }
        },
        "list_income_by_month.ListIncomeByMonthOutput": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Income"
                    }
                }
            }
        },
        "list_incomes.ListIncomesOutput": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Income"
                    }
                }
            }
        },
        "month_resume.MonthResumeOutput": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "total_each_category": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.ExpensesByCategory"
                    }
                },
                "total_expenses": {
                    "type": "number"
                },
                "total_incomes": {
                    "type": "number"
                }
            }
        },
        "service.ExpensesByCategory": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:5000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Financial Organizer API",
	Description:      "App to organize all your financial life",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
